"""Pydantic schemas for structured agent outputs."""

from keystone_agents.schemas.airtable import (
    AirtableBaseSchemaSummary,
    AirtableFieldSummary,
    AirtableTableSummary,
)
from keystone_agents.schemas.announcement_feed import (
    AnnouncementFeedEvidence,
    AnnouncementFeedItem,
)
from keystone_agents.schemas.approval import (
    ApprovalDecisionRecord,
    ApprovalRequest,
    ApprovalScope,
    ApprovalState,
)
from keystone_agents.schemas.automation import (
    AutomationArtifactRef,
    AutomationChannelBinding,
    AutomationFinding,
    AutomationInventoryReport,
    AutomationRun,
    AutomationSpec,
    ChiefOfStaffWriteRequest,
    NaturalInteractionResolution,
)
from keystone_agents.schemas.chief_of_staff import (
    ChiefOfStaffResult,
    ChiefOfStaffRouteRecommendation,
    ChiefOfStaffSourceRef,
)
from keystone_agents.schemas.company_profile import (
    ClaimEvidenceRecord,
    CompanyBriefFact,
    CompanyBriefSourceCitation,
    CompanyProfile,
    CompanyResearchFocusedBrief,
    SourceRecord,
)
from keystone_agents.schemas.contact_context import (
    ContactRecord,
    CRMAccountContext,
    LocalAccountContext,
)
from keystone_agents.schemas.context_pack import (
    ContextPack,
    ContextPackBase,
    ContextPackReadinessGate,
    GmailContextPack,
    MemoryContextRef,
    OpportunityContextPack,
    OutreachContactContext,
    OutreachContextPack,
    ProjectContextPack,
    ResearchContextPack,
)
from keystone_agents.schemas.crm import (
    CRMLeadRecord,
    CRMProviderName,
    CRMWriteOperation,
    CRMWriteResult,
    CRMWriteStatus,
)
from keystone_agents.schemas.decision_trace import (
    DecisionTrace as DecisionTrace,
)
from keystone_agents.schemas.decision_trace import (
    DecisionTraceComponent as DecisionTraceComponent,
)
from keystone_agents.schemas.email_style import EmailStyleProfile
from keystone_agents.schemas.email_triage import (
    EmailTriage,
    EmailTriageResult,
    GmailAttachmentMetadata,
    GmailLinkRecord,
    GmailMessageEnvelope,
    GmailPriorityGroupedMessage,
    GmailPriorityGroupingResult,
)
from keystone_agents.schemas.execution_request import (
    DirectAgentResponse,
    DirectAgentResponseInput,
    ExecutionContinuation,
    ExecutionEntrypoint,
    ExecutionPublicResult,
    ExecutionRequest,
    ExecutionResultStatus,
)
from keystone_agents.schemas.feedback import (
    OUTREACH_REVIEW_FEEDBACK_TAGS,
    SUGGESTED_FEEDBACK_TAGS,
    FeedbackRecord,
    FeedbackResponseResult,
    OperatorFeedbackCaptureFields,
    OperatorFeedbackRequest,
)
from keystone_agents.schemas.gmail_execution_plan import (
    GmailExecutionOperation,
    GmailExecutionPlan,
)
from keystone_agents.schemas.handoff import (
    HandoffContractError,
    HandoffContractName,
    HandoffContractResult,
    HandoffIssue,
    HandoffIssueSeverity,
    handoff_contracts_metadata,
    raise_for_invalid_handoffs,
    validate_business_research_analyst_to_outreach_composer,
    validate_opportunity_to_business_research_analyst,
    validate_orchestrator_to_approval_review,
    validate_outreach_composer_to_orchestrator,
    validate_pipeline_handoff_contracts,
)
from keystone_agents.schemas.handoff_types import (
    HANDOFF_TYPE_CONTRACT_VERSION,
    HandoffCompatibilityStatus,
    HandoffParsedOutputStatus,
    HandoffPayloadMode,
    HandoffTypeContract,
    build_handoff_type_contract,
)
from keystone_agents.schemas.manual_request_plan import (
    ManualRequestIntent,
    ManualRequestPlan,
    ManualTargetAgent,
    ManualTargetType,
)
from keystone_agents.schemas.memory import (
    ChiefOfStaffMemoryContext,
    MemoryItem,
    MemoryRetrievalResult,
    MemorySensitivity,
    MemoryType,
)
from keystone_agents.schemas.opportunity import (
    ExistingOpportunityState,
    Opportunity,
    OpportunityScoreBreakdown,
    OpportunityScoutResult,
    OpportunitySignal,
    OpportunitySourceBundle,
    OpportunityStateDecision,
)
from keystone_agents.schemas.opportunity import (
    OpportunityRecord as ScoutOpportunityRecord,
)
from keystone_agents.schemas.opportunity_search_plan import (
    OpportunitySearchObjective,
    OpportunitySearchPlan,
    OpportunityTargetEntity,
)
from keystone_agents.schemas.orchestrator import (
    HandoffSpec,
    OrchestratorDecision,
    OrchestratorOutputReview,
    OrchestratorOutputReviewScore,
    OrchestratorResult,
)
from keystone_agents.schemas.output_constraints import (
    InterpretedOutputConstraints,
    OutputConstraintValidation,
)
from keystone_agents.schemas.outreach import (
    ApprovedOutreachDraftingContext,
    CallPrepArtifact,
    FollowUpScheduleRecord,
    OutreachContext,
    OutreachDraft,
    OutreachDraftVariant,
    OutreachDraftVariantSet,
    OutreachExampleGuidance,
    OutreachLLMDraftPayload,
    OutreachTemplateContext,
    OutreachTrackingRecord,
    build_initial_outreach_tracking_record,
)
from keystone_agents.schemas.outreach import (
    OpportunityRecord as OutreachOpportunityRecord,
)
from keystone_agents.schemas.outreach_examples import (
    OutreachExampleDocument,
    OutreachExampleMessageSummary,
    OutreachExampleRecord,
    OutreachExampleRetrievalResult,
    OutreachExampleThread,
    RetrievedOutreachExample,
)
from keystone_agents.schemas.outreach_execution_plan import (
    OutreachExecutionOperation,
    OutreachExecutionPlan,
)
from keystone_agents.schemas.outreach_template import (
    OutreachTemplateBlock,
    OutreachTemplateRecord,
)
from keystone_agents.schemas.recommendation import (
    OpportunityContactPath,
    OpportunityEntity,
    OpportunityEntityType,
    RecommendationDecision,
    RecommendationIntakeResult,
    RecommendationNextStep,
    RecommendationScore,
)
from keystone_agents.schemas.research import (
    ResearchArticleSummary,
    ResearchBrief,
    ResearchBriefFact,
    ResearchSourceCitation,
    ResearchTargetType,
)
from keystone_agents.schemas.retrieval import RetrievalHint
from keystone_agents.schemas.review_card import (
    ReviewCard,
    ReviewEvidenceItem,
    ReviewObjectType,
    ReviewSourceItem,
)
from keystone_agents.schemas.table_mirror import (
    TableColumnMapping,
    TableMirrorExportRequest,
    TableMirrorExportResult,
    TableMirrorObjectType,
    TableMirrorProviderName,
    TableMirrorRecord,
)
from keystone_agents.schemas.web_data import (
    StructuredWebRecord,
    WebDataFieldSpec,
    WebDataSchemaMappingResult,
)
from keystone_agents.schemas.work_item import (
    WorkflowRunRequest,
    WorkflowRunResult,
    WorkItem,
    WorkItemApprovalGate,
    WorkItemArtifactRef,
    WorkItemBlocker,
    WorkItemEvent,
    WorkItemFact,
    WorkItemKind,
    WorkItemNextAction,
    WorkItemRoute,
    WorkItemSourceRef,
    WorkItemStatus,
    WorkItemTarget,
)

OpportunityRecord = ScoutOpportunityRecord

__all__ = [
    "CompanyProfile",
    "CompanyResearchFocusedBrief",
    "InterpretedOutputConstraints",
    "OutputConstraintValidation",
    "CompanyBriefFact",
    "CompanyBriefSourceCitation",
    "ClaimEvidenceRecord",
    "ApprovalDecisionRecord",
    "ApprovalRequest",
    "ApprovalScope",
    "ApprovalState",
    "AnnouncementFeedEvidence",
    "AnnouncementFeedItem",
    "AutomationArtifactRef",
    "AutomationChannelBinding",
    "AutomationFinding",
    "AutomationInventoryReport",
    "AutomationRun",
    "AutomationSpec",
    "ChiefOfStaffWriteRequest",
    "NaturalInteractionResolution",
    "AirtableBaseSchemaSummary",
    "AirtableFieldSummary",
    "AirtableTableSummary",
    "SourceRecord",
    "ContactRecord",
    "CRMAccountContext",
    "ContextPack",
    "ContextPackBase",
    "ContextPackReadinessGate",
    "GmailContextPack",
    "MemoryContextRef",
    "OpportunityContextPack",
    "OutreachContactContext",
    "OutreachContextPack",
    "ProjectContextPack",
    "ResearchContextPack",
    "CRMLeadRecord",
    "CRMProviderName",
    "CRMWriteOperation",
    "CRMWriteResult",
    "CRMWriteStatus",
    "ChiefOfStaffResult",
    "ChiefOfStaffRouteRecommendation",
    "ChiefOfStaffSourceRef",
    "LocalAccountContext",
    "EmailTriage",
    "EmailTriageResult",
    "GmailAttachmentMetadata",
    "GmailLinkRecord",
    "GmailMessageEnvelope",
    "GmailPriorityGroupedMessage",
    "GmailPriorityGroupingResult",
    "ExecutionContinuation",
    "DirectAgentResponse",
    "DirectAgentResponseInput",
    "ExecutionEntrypoint",
    "ExecutionPublicResult",
    "ExecutionRequest",
    "ExecutionResultStatus",
    "EmailStyleProfile",
    "OUTREACH_REVIEW_FEEDBACK_TAGS",
    "SUGGESTED_FEEDBACK_TAGS",
    "FeedbackRecord",
    "FeedbackResponseResult",
    "OperatorFeedbackCaptureFields",
    "OperatorFeedbackRequest",
    "HandoffContractError",
    "HandoffContractName",
    "HandoffContractResult",
    "HandoffIssue",
    "HandoffIssueSeverity",
    "HANDOFF_TYPE_CONTRACT_VERSION",
    "HandoffCompatibilityStatus",
    "HandoffParsedOutputStatus",
    "HandoffPayloadMode",
    "HandoffTypeContract",
    "build_handoff_type_contract",
    "handoff_contracts_metadata",
    "raise_for_invalid_handoffs",
    "validate_business_research_analyst_to_outreach_composer",
    "validate_opportunity_to_business_research_analyst",
    "validate_orchestrator_to_approval_review",
    "validate_outreach_composer_to_orchestrator",
    "validate_pipeline_handoff_contracts",
    "ChiefOfStaffMemoryContext",
    "MemoryItem",
    "MemoryRetrievalResult",
    "MemorySensitivity",
    "MemoryType",
    "ManualRequestIntent",
    "ManualRequestPlan",
    "ManualTargetAgent",
    "ManualTargetType",
    "GmailExecutionOperation",
    "GmailExecutionPlan",
    "Opportunity",
    "OpportunitySignal",
    "OpportunitySourceBundle",
    "OpportunityStateDecision",
    "ExistingOpportunityState",
    "OpportunityRecord",
    "OpportunityScoreBreakdown",
    "ScoutOpportunityRecord",
    "OutreachOpportunityRecord",
    "OpportunityScoutResult",
    "OutreachExecutionOperation",
    "OutreachExecutionPlan",
    "OpportunitySearchObjective",
    "OpportunitySearchPlan",
    "OpportunityTargetEntity",
    "HandoffSpec",
    "OrchestratorDecision",
    "OrchestratorOutputReview",
    "OrchestratorOutputReviewScore",
    "OrchestratorResult",
    "ResearchArticleSummary",
    "ResearchBrief",
    "ResearchBriefFact",
    "ResearchSourceCitation",
    "ResearchTargetType",
    "RetrievalHint",
    "ReviewCard",
    "ReviewEvidenceItem",
    "ReviewObjectType",
    "ReviewSourceItem",
    "WorkItem",
    "WorkItemApprovalGate",
    "WorkItemArtifactRef",
    "WorkItemBlocker",
    "WorkItemEvent",
    "WorkItemFact",
    "WorkItemKind",
    "WorkItemNextAction",
    "WorkItemRoute",
    "WorkItemSourceRef",
    "WorkItemStatus",
    "WorkItemTarget",
    "WorkflowRunRequest",
    "WorkflowRunResult",
    "StructuredWebRecord",
    "WebDataFieldSpec",
    "WebDataSchemaMappingResult",
    "ApprovedOutreachDraftingContext",
    "CallPrepArtifact",
    "FollowUpScheduleRecord",
    "OutreachExampleGuidance",
    "OutreachContext",
    "OutreachDraft",
    "OutreachDraftVariant",
    "OutreachDraftVariantSet",
    "OutreachLLMDraftPayload",
    "OutreachTemplateContext",
    "OutreachTrackingRecord",
    "build_initial_outreach_tracking_record",
    "OutreachExampleDocument",
    "OutreachExampleMessageSummary",
    "OutreachExampleRecord",
    "OutreachExampleRetrievalResult",
    "OutreachExampleThread",
    "RetrievedOutreachExample",
    "OutreachTemplateBlock",
    "OutreachTemplateRecord",
    "OpportunityContactPath",
    "OpportunityEntity",
    "OpportunityEntityType",
    "RecommendationDecision",
    "RecommendationIntakeResult",
    "RecommendationNextStep",
    "RecommendationScore",
    "TableColumnMapping",
    "TableMirrorExportRequest",
    "TableMirrorExportResult",
    "TableMirrorObjectType",
    "TableMirrorProviderName",
    "TableMirrorRecord",
]
