"""Export Keystone pipeline objects to a provider-neutral table mirror."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any

from keystone_agents.agents.opportunity_scout import scout_opportunities_fixture
from keystone_agents.agents.outreach_composer import (
    compose_outreach_draft_fixture,
    load_company_profile,
    load_contact_context,
    load_crm_account_context,
    load_opportunity_record,
)
from keystone_agents.company_research import research_company_fixture
from keystone_agents.interfaces.table_mirror import build_table_mirror_provider
from keystone_agents.reporting import (
    render_local_operator_dashboard,
    render_markdown_table,
    render_operator_dashboard_decision,
)
from keystone_agents.schemas.approval import ApprovalRequest
from keystone_agents.schemas.outreach import OutreachTrackingRecord
from keystone_agents.schemas.table_mirror import (
    TableMirrorExportResult,
    TableMirrorObjectType,
    TableMirrorProviderName,
    normalize_table_mirror_object_type,
)
from keystone_agents.storage.sqlite_store import SQLiteStore, database_url_from_env

PROJECT_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_ROOT = PROJECT_ROOT / "tests" / "fixtures"
OBJECT_TYPE_CHOICES = [item.value for item in TableMirrorObjectType]
PROVIDER_CHOICES = [item.value for item in TableMirrorProviderName]


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Export Keystone pipeline objects to a dry-run table mirror."
    )
    parser.add_argument(
        "--provider",
        default=TableMirrorProviderName.DRY_RUN.value,
        choices=PROVIDER_CHOICES,
        help="Mirror provider. Live providers are placeholders.",
    )
    parser.add_argument(
        "--object-type",
        default=None,
        choices=OBJECT_TYPE_CHOICES,
        help="Keystone object type to mirror.",
    )
    parser.add_argument(
        "--source",
        choices=["fixtures", "sqlite"],
        default="fixtures",
        help="Record source for table exports. SQLite uses DATABASE_URL.",
    )
    parser.add_argument(
        "--dashboard",
        action="store_true",
        help="Export a local operator dashboard from SQLite instead of one table.",
    )
    parser.add_argument(
        "--dashboard-decision",
        action="store_true",
        help="Print the local operator dashboard decision and later API requirements.",
    )
    parser.add_argument(
        "--database-url",
        default=None,
        help="SQLite URL for --source sqlite or --dashboard.",
    )
    parser.add_argument("--limit", type=int, default=10, help="Maximum rows per section.")
    parser.add_argument(
        "--live",
        action="store_true",
        help="Explicitly request a live provider. Live providers are not implemented yet.",
    )
    parser.add_argument("--json", action="store_true", help="Print JSON instead of text.")
    return parser


def _approval_records() -> list[ApprovalRequest]:
    return [
        ApprovalRequest(
            object_type="outreach_draft",
            object_id="dry-run-draft-1",
            summary="Review draft-only outreach before any external use.",
            draft_text="Dry-run draft artifact requires human approval.",
            decision="pending",
            scope="send",
            risk_flags=[],
            notes="Generated by export_pipeline_table.py dry-run fixture.",
        )
    ]


def _contact_records() -> list[Any]:
    return [load_contact_context("sample_contact_curebase_approved")]


def _crm_context_records() -> list[Any]:
    return [load_crm_account_context("sample_crm_context_curebase")]


def _outreach_tracking_records() -> list[Any]:
    return [
        OutreachTrackingRecord(
            draft_id="dry-run-draft-1",
            company_name="Curebase",
            contact_name="Dr. Priya Shah",
            lifecycle_status="draft_pending_approval",
            outreach_sent=False,
            reply_received=False,
            outcome="unknown",
            next_step="Human review required before external use.",
        )
    ]


def fixture_records_for_object_type(object_type: TableMirrorObjectType | str) -> list[Any]:
    """Build deterministic dry-run records for one mirror object type."""

    resolved_type = normalize_table_mirror_object_type(object_type)
    if resolved_type == TableMirrorObjectType.OPPORTUNITIES:
        return list(scout_opportunities_fixture(max_results=5).records)
    if resolved_type == TableMirrorObjectType.COMPANIES:
        return [
            research_company_fixture(
                company_name="Curebase",
                fixture_json=FIXTURE_ROOT / "sample_company_curebase.json",
            )
        ]
    if resolved_type == TableMirrorObjectType.DRAFTS:
        return [
            compose_outreach_draft_fixture(
                company_profile=load_company_profile("sample_company_curebase"),
                opportunity_record=load_opportunity_record("sample_lead_curebase"),
                contact_context=load_contact_context("sample_contact_curebase_approved"),
                crm_context=load_crm_account_context("sample_crm_context_curebase"),
            )
        ]
    if resolved_type == TableMirrorObjectType.APPROVALS:
        return _approval_records()
    if resolved_type == TableMirrorObjectType.FEEDBACK:
        return [
            {
                "id": 1,
                "object_type": "outreach_draft",
                "object_id": "dry-run-draft-1",
                "rating": "good",
                "tags": ["well_sourced"],
                "notes": "Dry-run fixture feedback for local review.",
                "created_at": "2026-04-21T12:00:00Z",
            }
        ]
    if resolved_type == TableMirrorObjectType.AUDIT_RECORDS:
        return [
            {
                "id": 1,
                "agent_name": "opportunity_scout",
                "status": "success",
                "dry_run": True,
                "input_summary": "behavioral health AI",
                "created_at_utc": "2026-04-21T12:00:00Z",
            }
        ]
    if resolved_type == TableMirrorObjectType.CONTACTS:
        return _contact_records()
    if resolved_type == TableMirrorObjectType.CRM_CONTEXTS:
        return _crm_context_records()
    if resolved_type == TableMirrorObjectType.OUTREACH_TRACKING:
        return _outreach_tracking_records()
    raise AssertionError(f"Unhandled object type: {resolved_type}")


def sqlite_records_for_object_type(
    object_type: TableMirrorObjectType | str,
    *,
    database_url: str | None = None,
    limit: int = 10,
) -> list[Any]:
    """Load local SQLite records for provider-neutral table export."""

    store = SQLiteStore(database_url or database_url_from_env())
    resolved_type = normalize_table_mirror_object_type(object_type)
    limit = max(limit, 0)
    if resolved_type == TableMirrorObjectType.OPPORTUNITIES:
        return [
            _opportunity_export_record(row)
            for row in _latest(store.fetch_all("opportunities"), limit)
        ]
    if resolved_type == TableMirrorObjectType.COMPANIES:
        return [_company_export_record(row) for row in _latest(store.fetch_all("companies"), limit)]
    if resolved_type == TableMirrorObjectType.DRAFTS:
        tracking_by_draft_id = _latest_tracking_by_draft_id(store.fetch_all("outreach_tracking"))
        return [
            _draft_export_record(row, tracking_by_draft_id.get(str(row.get("id"))))
            for row in _latest(store.fetch_all("outreach_drafts"), limit)
        ]
    if resolved_type == TableMirrorObjectType.APPROVALS:
        queue_items = [item.model_dump(mode="json") for item in store.get_pending_approvals(None)]
        if queue_items:
            return list(reversed(queue_items))[:limit]
        return [
            _approval_export_record(row) for row in _latest(store.fetch_all("approvals"), limit)
        ]
    if resolved_type == TableMirrorObjectType.FEEDBACK:
        return _latest(store.list_feedback(), limit)
    if resolved_type == TableMirrorObjectType.AUDIT_RECORDS:
        return _latest(store.fetch_all("agent_runs"), limit)
    if resolved_type == TableMirrorObjectType.CONTACTS:
        return [_contact_export_record(row) for row in _latest(store.fetch_all("contacts"), limit)]
    if resolved_type == TableMirrorObjectType.CRM_CONTEXTS:
        return [
            _crm_context_export_record(row)
            for row in _latest(store.fetch_all("crm_contexts"), limit)
        ]
    if resolved_type == TableMirrorObjectType.OUTREACH_TRACKING:
        return [
            _tracking_export_record(row)
            for row in _latest(store.fetch_all("outreach_tracking"), limit)
        ]
    raise AssertionError(f"Unhandled object type: {resolved_type}")


def render_export(result: TableMirrorExportResult) -> str:
    """Render a concise human-readable mirror preview."""

    lines = [
        "# Keystone Table Mirror Export",
        "",
        f"Provider: {result.provider.value}",
        f"Object type: {result.object_type.value}",
        f"Table: {result.table_name}",
        f"Dry run: {str(result.dry_run).lower()}",
        f"Rows: {len(result.records)}",
        "",
        "## Column Mapping",
    ]
    lines.extend(f"- {mapping.source_field} -> {mapping.column_name}" for mapping in result.columns)
    lines.extend(["", "## Rows", ""])
    if not result.records:
        lines.append("No rows found.")
        return "\n".join(lines)

    headers = ["Record ID", *[mapping.column_name for mapping in result.columns]]
    rows = [
        [record.record_id, *[record.fields.get(mapping.column_name) for mapping in result.columns]]
        for record in result.records
    ]
    lines.append(render_markdown_table(headers, rows))
    return "\n".join(lines)


def main() -> int:
    args = build_parser().parse_args()
    if args.limit < 0:
        raise SystemExit("--limit must be zero or greater.")
    if args.dashboard_decision:
        print(render_operator_dashboard_decision())
        return 0
    if args.dashboard:
        store = SQLiteStore(args.database_url or database_url_from_env())
        print(render_local_operator_dashboard(store, limit=args.limit))
        return 0
    if not args.object_type:
        raise SystemExit("--object-type is required unless --dashboard is passed.")
    try:
        provider = build_table_mirror_provider(args.provider, live=args.live)
        records = (
            sqlite_records_for_object_type(
                args.object_type,
                database_url=args.database_url,
                limit=args.limit,
            )
            if args.source == "sqlite"
            else fixture_records_for_object_type(args.object_type)
        )
        result = provider.export_records(args.object_type, records)
    except (NotImplementedError, RuntimeError, ValueError) as exc:
        raise SystemExit(str(exc)) from exc

    if args.json:
        print(result.model_dump_json(indent=2))
    else:
        print(render_export(result))
    return 0


def _latest(rows: list[dict[str, Any]], limit: int) -> list[dict[str, Any]]:
    return list(reversed(rows))[:limit]


def _json_dict(value: Any) -> dict[str, Any]:
    if isinstance(value, dict):
        return value
    if not value:
        return {}
    try:
        loaded = json.loads(str(value))
    except ValueError:
        return {}
    return loaded if isinstance(loaded, dict) else {}


def _opportunity_export_record(row: dict[str, Any]) -> dict[str, Any]:
    payload = _json_dict(row.get("opportunity_json"))
    return {
        **payload,
        "company_name": payload.get("company_name") or row.get("target_company"),
        "opportunity_type": payload.get("opportunity_type") or row.get("opportunity_type"),
        "priority_score": payload.get("priority_score") or row.get("priority_score"),
        "recommended_next_step": payload.get("recommended_next_step"),
    }


def _company_export_record(row: dict[str, Any]) -> dict[str, Any]:
    payload = _json_dict(row.get("profile_json"))
    return {
        **payload,
        "name": payload.get("name") or row.get("company_name"),
        "website": payload.get("website") or row.get("company_url"),
        "consulting_fit_score": payload.get("consulting_fit_score")
        or row.get("consulting_fit_score"),
        "confidence_score": payload.get("confidence_score") or row.get("confidence_score"),
    }


def _draft_export_record(
    row: dict[str, Any],
    tracking: dict[str, Any] | None = None,
) -> dict[str, Any]:
    payload = _json_dict(row.get("draft_json"))
    approval_state = payload.get("approval_state") or row.get("approval_state")
    tracking_payload = (
        _tracking_export_record(tracking)
        if tracking is not None
        else _default_tracking_export_record(row, approval_state=approval_state)
    )
    return {
        **payload,
        "company_name": payload.get("company_name") or row.get("company_name"),
        "contact_name": payload.get("contact_name") or row.get("contact_name"),
        "email_subject": payload.get("email_subject") or row.get("email_subject"),
        "email_body": payload.get("email_body_summary") or row.get("email_body"),
        "approval_state": approval_state,
        **tracking_payload,
    }


def _approval_export_record(row: dict[str, Any]) -> dict[str, Any]:
    return {
        "object_type": row.get("object_type"),
        "object_id": row.get("object_id"),
        "summary": row.get("notes") or row.get("decision"),
        "decision": row.get("decision"),
        "scope": row.get("scope"),
        "reviewer": row.get("reviewer"),
        "timestamp": row.get("timestamp"),
        "notes": row.get("notes"),
    }


def _contact_export_record(row: dict[str, Any]) -> dict[str, Any]:
    payload = _json_dict(row.get("contact_json"))
    return {
        **payload,
        "contact_name": payload.get("contact_name") or row.get("contact_name"),
        "company_name": payload.get("company_name") or row.get("company_name"),
        "role_title": payload.get("role_title") or row.get("role_title"),
        "contact_email": payload.get("contact_email") or row.get("contact_email"),
        "source": payload.get("source") or row.get("source"),
        "source_id": payload.get("source_id") or row.get("source_id"),
        "approval_state": payload.get("approval_state") or row.get("approval_state"),
    }


def _crm_context_export_record(row: dict[str, Any]) -> dict[str, Any]:
    payload = _json_dict(row.get("context_json"))
    return {
        **payload,
        "company_name": payload.get("company_name") or row.get("company_name"),
        "account_stage": payload.get("account_stage") or row.get("account_stage"),
        "account_owner": payload.get("account_owner") or row.get("account_owner"),
        "source": payload.get("source") or row.get("source"),
        "source_id": payload.get("source_id") or row.get("source_id"),
        "approval_state": payload.get("approval_state") or row.get("approval_state"),
    }


def _tracking_export_record(row: dict[str, Any]) -> dict[str, Any]:
    payload = _json_dict(row.get("tracking_json"))
    return {
        **payload,
        "id": payload.get("id") or row.get("id"),
        "draft_id": payload.get("draft_id") or row.get("draft_id"),
        "company_name": payload.get("company_name") or row.get("company_name"),
        "contact_name": payload.get("contact_name") or row.get("contact_name"),
        "channel": payload.get("channel") or row.get("channel"),
        "lifecycle_status": payload.get("lifecycle_status") or row.get("lifecycle_status"),
        "outreach_sent": _boolish(payload.get("outreach_sent", row.get("outreach_sent"))),
        "sent_at": payload.get("sent_at") or row.get("sent_at"),
        "sent_by": payload.get("sent_by") or row.get("sent_by"),
        "sent_via": payload.get("sent_via") or row.get("sent_via"),
        "reply_received": _boolish(payload.get("reply_received", row.get("reply_received"))),
        "reply_received_at": payload.get("reply_received_at") or row.get("reply_received_at"),
        "reply_summary": payload.get("reply_summary") or row.get("reply_summary"),
        "outcome": payload.get("outcome") or row.get("outcome"),
        "outcome_notes": payload.get("outcome_notes") or row.get("outcome_notes"),
        "next_step": payload.get("next_step") or row.get("next_step"),
        "last_checked_at": payload.get("last_checked_at") or row.get("last_checked_at"),
    }


def _default_tracking_export_record(
    row: dict[str, Any],
    *,
    approval_state: Any,
) -> dict[str, Any]:
    state_text = str(approval_state or "").lower()
    lifecycle_status = (
        "draft_approved" if state_text.startswith("approved") else "draft_pending_approval"
    )
    return {
        "draft_id": str(row.get("id") or ""),
        "lifecycle_status": lifecycle_status,
        "outreach_sent": False,
        "sent_at": "",
        "reply_received": False,
        "reply_received_at": "",
        "outcome": "unknown",
        "outcome_notes": "",
        "next_step": "Review and update outreach tracking manually.",
    }


def _latest_tracking_by_draft_id(rows: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    latest: dict[str, dict[str, Any]] = {}
    for row in rows:
        draft_id = str(row.get("draft_id") or "")
        if draft_id:
            latest[draft_id] = row
    return latest


def _boolish(value: Any) -> bool:
    if isinstance(value, bool):
        return value
    if isinstance(value, int | float):
        return bool(value)
    return str(value).strip().lower() in {"1", "true", "yes", "y"}


if __name__ == "__main__":
    raise SystemExit(main())
